### ISSUE TITLE
Add support for more options in facet searching - i.e. exclude

### ISSUE THREAD

**Issue by Rio517** [karmi/retire#116]
Hi, 

I was trying to pass a list of stopwords to a terms facet, but the option wasn't getting pass through, since you're adding any other options at the same level as :terms.  

I just did this: https://github.com/Rio517/tire/commit/91e86a31f9e6cdc9acb401456a1b3216c8fedd25

-Mario

Update: accidentally forgot which keys get overwritten in commit I referenced earlier.  Fixed.

**Comment by karmi** [comment]
Hi Mario,

this has slipped under my radar, sorry. This seems like the `update(options)` call is incorrectly nested, is that it?

Based on a quick look at http://www.elasticsearch.org/guide/reference/api/search/facets/terms-facet.html my code is actually totally messed up, since there aren't any top level options for a terms facet. Will look into that.

**Comment by karmi** [comment]
@Rio517: The issue should be fixed now, thanks for the report -- the passing of options in `date` and `terms` facet was incorrect.

**Comment by Rio517** [comment]
Awesome! Thanks!
