### ISSUE TITLE
Why do I need a wildcard for what should be an exact match?

### ISSUE THREAD

**Issue by superplussed** [karmi/retire#143]
I have a class with a field mapped like this:

Tire.index(HandResults.index_name) do
      create mappings: {
        show: {
          properties: {
            id: {type: 'string', analyzer: 'keyword'},
            p_id: {type: 'string', analyzer: 'keyword'}, 
            ...

If I take a look at the data after performing a bulk import, I can see an example of the field I'm interested in:

.."st"=>1, "p_id"=>"PST_nuns", ..

If I query on the field though, I need to use the wildcard to get any results:

> > HandResults.search("p_id:PST_nuns*").results.count
> > => 10
> > HandResults.search("p_id:PST_nuns").results.count
> > => 0

Is there a reason for this?

Thanks!

**Comment by vhyza** [comment]
Hello,

you can try to take a look if mapping is correctly created `http://localhost:9200/INDEX_NAME/_mapping`.

`PST_nuns` is unique id? I'm asking because `keyword` analyzer create only one token into index. Whole id string. (according http://www.elasticsearch.org/guide/reference/index-modules/analysis/keyword-analyzer.html) 

So if you have for example `PST_nuns_and_some_prefix` id then searching for `PST_nuns` won't work, because in index is whole `PST_nuns_and_some_prefix`.

**Comment by karmi** [comment]
Hi, not really -- such behaviour is weird. Are you sure the index is created with proper mapping and that you're putting in docs of proper `:type`?

**Comment by superplussed** [comment]
Sorry guys, I think the mapping was incorrect, the behavior went away after some changes.  Thanks!
