### ISSUE TITLE
Tire HTTP client [Was: Shellouts performance]

### ISSUE THREAD

**Issue by ifesdjeen** [karmi/retire#166]
I noticed today [rest deleted by the author]

**Comment by michaelklishin** [comment]
Faraday is definitely the way to go.

**Comment by ifesdjeen** [comment]
Sorry, my bad
that issue is absolutely irrelevant. I completely misunderstood some things here.

**Comment by karmi** [comment]
@ifesdjeen: No problem :) Were those are the `curl`-formatted debug lines you found?

**Comment by karmi** [comment]
By the way, there **is** a _Curb_-based [client](https://github.com/karmi/tire/blob/master/lib/tire/http/clients/curb.rb). See the benchmarks: https://gist.github.com/1204159.

Rolling custom client is very simple with _Tire_. But, yes, I'd like to convert the HTTP stuff to _Faraday_ some day in the future. It's a relatively trivial refactoring.

So far, it's been on the “nice to have” list for me, since there are many more important features  -- maybe I'm wrong.
