### ISSUE TITLE
Adding scan support to the Tire DSL

### ISSUE THREAD

**Issue by mikegrassotti** [karmi/retire#196]
I needed support for scan queries in my app, so I drafted a quick extension to the Tire DSL. Is anyone else working on this feature? If there's interest I'd be happy to submit what I have so far as a pull request...

**Comment by erickt** [comment]
I'm interested! I was just about to start working on that.

**Comment by mikegrassotti** [comment]
OK, let's give it a shot. I just pushed my changes here:

https://github.com/grasscode/tire/commit/63fefb9b56073180356e676fea2e327adc09f7dc

**Comment by erickt** [comment]
Great, thanks. I've got two comments. First, could you factor out the scrolling code into it's own class/dsl? Second, could you add a `search_type` option to `Search` and use that instead of hardcoding `search_type=scan`? It's just shuffling a couple things around in your code and it'll be a bit more flexible.

**Comment by erickt** [comment]
@grasscode: another thought. The `size` argument should be lifted out of the `Scan` module, since `Search` already provides it.

**Comment by erickt** [comment]
@grasscode: I needed search_type for my own purposes, so I have a pull request here for [here](https://github.com/karmi/tire/pull/198).

**Comment by mikegrassotti** [comment]
@erickt thx. I'll have a look at your search_type code.
