### ISSUE TITLE
Bulk deleting/updates

### ISSUE THREAD

**Issue by amfeng** [karmi/retire#219]
The tire examples/documentation only refer to using ES's bulk API in the context of adding documents. Does tire support bulk deleting or updating?

**Comment by karmi** [comment]
Only adding documents is supported at the moment.

**Comment by JamesHarrison** [comment]
Has this changed? Specifically I'm looking at updating a mapping and updating all documents without doing a complete delete/recreation since that takes about 7 hours and requires a site outage, which isn't ideal. What's the current best way to go about this?

**Comment by karmi** [comment]
@JamesHarrison Updating mapping _can_ require full reindex, when you do an incompatible change.

Another option which wouldn't require accessing your database (and thus would be very, very fast) is to use [`Index#reindex`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L148-157), see karmi/tire@88b5bc7 . It's optimal when you use index aliases (see karmi/tire@67aa3a4) in combination with that, since then you can prevent downtime.

**Comment by karmi** [comment]
@afeng Bulk create/delete is now supported and released as 0.5.1. Changes: https://github.com/karmi/tire/compare/4e85109...1c0d043
