### ISSUE TITLE
Setting up analyzer with no stopword detection

### ISSUE THREAD

**Issue by joshcutler** [karmi/retire#260]
This isn't a problem with tire, so if there is a better place for me to ask please let me know and close this issue out.

I had an existing index on text that had the standard analyzer being used.  I recently realized that the stopword list includes "will" which is bad because much of the text that is being searched is peoples' names and will is fairly common.

I am trying to create a custom analyzer that doesn't use the stopword filter like so:

``` ruby
  include Tire::Model::Search
  include Tire::Model::Callbacks
  tire.settings :analysis => {
      :analyzer => {
        :no_stopwords => {
          "type" => "custom",
          "tokenizer" => "standard",
          "filter" => ["standard", "lowercase"]
        }
      }
    } do
    tire.mapping do
      indexes :keywords, :analyzer => "no_stopwords"
    end
  end
```

And it does not seem to be working.  My questions are:

A) Is this properly specified?
B) What do I need to do to get this reflected in my index.  Do I need to destroy and recreate my index?

Thanks,
-=Josh

**Comment by karmi** [comment]
Hi Josh, your settings and mapping seem to be correct, check http://pastie.org/3521311 for working example.

If you're changing an existing property (and I'd bet you are), you _have_ to reindex the data, ie. destroy and import again. Do check the mapping when you create the new index, either with `curl localhost:9200/YOURINDEX/_mapping`, or with _Tire_ (`p Tire::Index.new('YOURINDEX').mapping`).

**Comment by joshcutler** [comment]
Great, thanks for getting back to me so quickly.  Just to be clear (because creating my index takes ~24 hours), I have to blow away the whole index, not just reindex the items where this situation was occurring?  How do people generalyl handle tweaks to the search index in production environments?

Thanks again,
-=Josh

**Comment by karmi** [comment]
Yes, due to the way the search engine analyzes your docs, the whole index must be recreated with new settings (ie. "tokenize the `keywords` property of this type of document in _this_ way"), and the data must be imported again, so it is properly chopped & processed by the newly set analyzer...

Of course it's painful to do it, but there's no way around it, and you have to do it from time to time, even after things settle down a bit when you discover how you need to analyze your data...

You can use index aliases in ES to recreate your index as `myindex_A`, while keeping the `myindex` in production. Once the import is finished, you can delete the `myindex` index,create an alias `myindex` pointing to `myindex_A`, without much downtime.

Check the discussion here: https://github.com/karmi/tire/issues/62#issuecomment-1625299, it is a similar issue... Ping back here, or preferably at the #elasticsearch IRC channel if you need more info...

**Comment by joshcutler** [comment]
Thanks a lot.  This really helps.
