### ISSUE TITLE
Import broken

### ISSUE THREAD

**Issue by sarmiena** [karmi/retire#272]
Tire::Index#import iteration algorithm does not guarantee unique records. Using kaminari & Postgres, I get SQL commands like this:

`SELECT  "products".* FROM "products"  LIMIT 1000 OFFSET 1000`

Note that without an `order by` clause, OFFSET will return random records since it doesn't have a concept of a cursor. Even kaminari addresses this concern in their documentation: https://github.com/amatsuda/kaminari/wiki/Kaminari-recipes

Also, why the need to use an external gem (will_paginate or kaminari) to iterate over records when ActiveRecord already has #find_in_batches and Mongoid has #batch_size (https://github.com/mongoid/mongoid/issues/1334)

**Comment by karmi** [comment]
> why the need to use an external gem (...) to iterate over records when ActiveRecord already has #find_in_batches and Mongoid has #batch_size

Because that's ActiveRecord (or Mongoid) specific interface. There's no ActiveModel standard for batch find. Many people, me included don't care about ActiveRecord (or Mongoid) and use different storage systems with different adapters.

> Tire::Index#import iteration algorithm does not guarantee unique records. Using kaminari & Postgres (...)

Where's _Tire_ behaving strangely here? Is there a _Tire_ issue then? Could you use `will_paginate` instead of Kaminari?

**Comment by sarmiena** [comment]
After further review, I simply put order() inside of the #paginate method.

My bad.

**Comment by karmi** [comment]
No problem. I'm using `will_paginate`, mostly.
