### ISSUE TITLE
Explictly specifying type 

### ISSUE THREAD

**Issue by philly-mac** [karmi/retire#275]
Hi,

I don't know if it is just me, but I find it kind of annoying and even irregular that in the tire code you can specify the type like this when removing from the index

``` ruby
def remove(*args)
      if args.size > 1
        type, document = args
        id = get_id_from_document(document) || document
      else
        document = args.pop
        type = get_type_from_document(document)
        id = get_id_from_document(document) || document
      end
```

but when you are adding to the index you have to place the type within the structure of the hash or create a method that returns the type on the object

i.e.

``` ruby
    def store(*args)
      document, options = args
      type = get_type_from_document(document)

      if options
        percolate = options[:percolate]
        percolate = "*" if percolate === true
      end
```

In my opinion, type should always be allowed to be specified just like how you can when you remove from the index.
Personally, looking at the code, it seems kind of hacky the way the getting the type works. And furthermore, the way it is implemented means that you cannot pass in a json string to store, and specify the type as well. In fact a few weeks ago, a lot of my tests started to break because of this. Because there is no explicit way to set the type in store, I had a method that was returning the type for the index, but all of a sudden it started using "document" as the type, and I had no idea why. Looking at the code, it seems as though if you have a type that is the same as the type of class it will not use that type, why? Anyway, I had to (what feels to me like a hack) implement another method document_type that returned the type. But now I am wondering how long that is going to be stable as the type. And having this sort of way that you can specify the type just seems like not wanting to commit to something (for whatever reason) and just have a method signature like

``` ruby
store(type, document, *args)
```

That would have been the logical choice of method signature for me.

Let me know what you think.

**Comment by karmi** [comment]
Hi, it took me a while to decipher what exact issue you are experiencing. I think I understand now and I am grateful for the issue, because it shed some light on important matters.

1/ You're right that the interface is asymmetric and absolutely _not_ elegant the way it is.

2/ I don't know what are you referring to as "hacky", though. Do you consider getting type from the document in [`Index#get_type_from_document`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L265-279) as "hacky"? I tend to think the logic is very clear and the code is quite robust.

2/ The real problem is that `remove` is symmetric with `store`, and not with `retrieve`. In ElasticSearch, _get_ and _delete_ takes document type and document ID as arguments. This is something we'll fix as soon as possible.

3/ You can see, that the interface you're proposing has in fact been there previously, but was removed for good reasons. See commits 7daddb7, b06469c, 7749f0a, a05e4bf. The new interface is more fluid and convenient. It _does_ suffer with the aforementioned assymetry, though. The old interface _was_ "hacky" in trying to figure out what exactly are you passing to the method.

3/ Obviously, _Tire_ assumes certain things about the documents you're passing to the `Index#store` functions. They must be objects responding to `document_type`, `type` or `_type` methods, or Hashes with a `type` or `_type` property. I tend to think this is a very transparent and simple contract for your objects.

4/ It seems like you are passing a JSON string to the `Index#store` method. While this has been supported in the previous interface, it does not make any sense right now -- you just don't have _any means whatsoever_ to pass a proper document type. This feature has been just deprecated in 5739059.

> Looking at the code, it seems as though if you have a type that is the same as the type of class it will not use that type, why?

That's a guard against inadverently storing classes as their "native" `type` in Ruby. It would be surprising if Tire would do that. For any object you intend to pass to _Tire_, it's safer to implement `document_type`.

> Anyway, I had to (what feels to me like a hack) implement another method document_type that returned the type.

Again, I don't understand why you'd consider this a "hack", but that's precisely the contract _Tire_ expects from your objects. See http://karmi.github.com/tire/#section-18. If there's an issue with `document.respond_to?(:type) && document.type != document.class` (notice the capitalization in the `Article` class at the link), I'd be happy to have a clear case which demonstrates it!

If I misunderstood the problems you're having, please explain it more!

**Comment by philly-mac** [comment]
Well my feeling of hacky, comes from what you term a "more fluid and convenient". I know ruby is a "many ways to do the same thing" type of language, but I would prefer to be able to explictly pass through the type to the store method. And not have have to embed it in a method that Tire then checks to get the type. 

I guess it just comes down to a difference of taste at the end of the day. For me `store(type, document, *args)` and `remove(type, id, *args)` is more intuitive, especially if I was just guessing. 

Now I am doing something like

``` ruby
    def self.index(object)
      search_index = Tire.index(AppConfig.elastic_search.index)
      search_index.store(to_indexed_hash(object))
      search_index.refresh
    rescue Exception => e
      Padrino.logger.error "Error: #{e}"
    end

    def self.to_indexed_hash(object)
      locum.attributes.merge({
        :type       => type,
        :addresses  => locum.addresses.map {|a| a.attributes},
      })
    end
```

Which works, and abstracts the whole search thing in my code to this small class. But still feels wrong somehow to be puting the type in the hash. Not 100% sure why, but it does. When/if I figure it out in my own mind I may add to this issue in future. 

The other things is I feel the README is too "here and there". In fact the best way I would describe it is, if I was going over a topic and was just trying to get down on paper everything that thing did. But then at the end I didn't go back and restructre it completely, or format it to make it easy to read. I found that too many time I had to look for the type of code that I wanted to do in the example file, or try and look if I could find an example piece of code that did it. But like I said, I guess it is just a difference in taste. I think I just have a predefined idea of what logical is, and Iif  don't see it, it throws me off a bit.

**Comment by karmi** [comment]
> Well my feeling of hacky, comes from what you term a "more fluid and convenient".
> (...) but I would prefer to be able to explictly pass through the type to the store method.
> And not have have to embed it in a method that Tire then checks to get the type.

You have to, in fact, _explicitely_ pass the type to the `store` method: either as a `document_type` method for objects, or `type|_type` property of a Hash. You just don't pass it as a separate argument.

> I guess it just comes down to a difference of taste at the end of the day.
> For me store(type, document, *args) and remove(type, id, *args) is more intuitive, especially if I was just guessing.

Yes, it is more explicit. Given how transparent the logic in [`Index#get_type_from_document`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L265-279) is, I'd say we don't have to be so explicit.

> The other things is I feel the README is too "here and there".

A proper documentation is definitely something which needs more work, once we sort out the current situation with dozens of pull requests and important features missing....

Regarding the Ruby code you posted, I have the feeling you make things very complicated for you with no real benefit...

1/ If you're storing a standard ActiveModel compliant object, why not just call `as_json(... lots of options ...)` in it's `to_indexed_json` method?

2/ If you're storing some other object, why not just build the Hash manually and transparently, again in the `to_indexed_json` method?
