### ISSUE TITLE
Carrierwave & Tire Conflicting

### ISSUE THREAD

**Issue by kyledecot** [karmi/retire#307]
I recently ran into a problem when trying to add both [Carrierwave](https://github.com/jnicklas/carrierwave) and [Tire](https://github.com/karmi/tire) to one of my models. The problem seems to be caused by the `serializable_hash` method which is used by both gems. I have included a link to the related SO post:

http://stackoverflow.com/questions/9961477/carrierwave-tire-conflicting

**Comment by karmi** [comment]
Carrierware seems to redefine `serializable_hash`, and maybe it's breaking stuff for other gems -- be sure to file an issue with them.

Anyways, you can just redefine the `to_indexed_json` method:

``` ruby
def to_indexed_json
  self.as_json
end
```

so _Tire_ won't rely on compatible `serializable_hash`...

When you find the solution, please close the ticket and the SO question, otherwise, ping here!

**Comment by karmi** [comment]
@kyledecot Hi, any news on this? Is your issue solved?

**Comment by kyledecot** [comment]
Yes. This has been fixed in the most recent version of Carrierwave. Sorry for the delayed response.

**Comment by karmi** [comment]
@kyledecot Perfect, thanks!
