### ISSUE TITLE
Add possibility to return maximum N results

### ISSUE THREAD

**Issue by xdmx** [karmi/retire#319]
I love Tire, but one great feature I miss from thinking sphinx is the ability to limit the max results, which is used for pagination too.

For example, you have 2 millions results, the total_entries will be 2 millions, but the effective results for the pagination will be eg 1000 (so if per_page => 20, there will be 50 pages).

This is very useful in order to block users to go to the real last page, which would be like page #100000, as with some simple queries and sorting would take a lot of time to get that result.

I've already added that if the page is greater than 50 then set 50, but the problem with will paginate it's that it shows the last pages, so 99998, 99999, 100000, when the user click on them he'll get page 50, that's not a great user experience

**Comment by karmi** [comment]
Hi, I think for large data sets, it does not make much sense to use pagination?

The proper solution from the user experience standpoing is to offer the "Load More" link and the total number of documents? Because, when the total entries is 2 millions, you:

a) are either interested in aggregations on these results, so don't care about paginating results anyway,
b) should improve your query to get back a better result set.

Cf.:
- http://railscasts.com/episodes/114-endless-page
- http://railscasts.com/episodes/114-endless-page-revised

**Comment by xdmx** [comment]
Hi Karmi, yes, the endless page is a useful solution, but not for all the scenario. For sites like twitter, facebook, etc is perfect, but think about an ecommerce, comparator, etc where you have a lot of items, endless pagination is bad for the user (that what they told us, we tested a/b) because they click on an item and when they go back with the browser they'll need to scroll everything again.
The query takes in consideration various values so already filter something out, but generic one can be done (like all the items under a given price), and that way the risk is showing page #123456 which will slow down a lot when clicked

**Comment by karmi** [comment]
I don't see a clean way how to add a feature like this right now. I don't see good documentation on that in ThinkingSphinx either...
