### ISSUE TITLE
Some weird bug break everything

### ISSUE THREAD

**Issue by xdmx** [karmi/retire#343]
Hi, it's the second time that I've found that the elastic search index has into it some ids of records that are not in the db anymore. I'm investigating this on my app, as it's reeeally strange as they can't be deleted, and I've not done it manually (my first guess would be some kind of rollback on transactions failures that tire/ES manage but the record is then removed, but not sure 100%)

Btw, tire should be nicer on managing this, currently is used the .find(ids) method: https://github.com/karmi/tire/blob/master/lib/tire/results/collection.rb#L59

When an id is not found, it throws a very bad exception (I'm still using tire 0.3.12, but it's still valid on the current version):

```
(found 71 results, but was looking for 72)
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.2.3/lib/active_record/relation/finder_methods.rb:369:in `find_some'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.2.3/lib/active_record/relation/finder_methods.rb:314:in `find_with_ids'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.2.3/lib/active_record/relation/finder_methods.rb:107:in `find'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.2.3/lib/active_record/relation/finder_methods.rb:101:in `find'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/activerecord-3.2.3/lib/active_record/querying.rb:5:in `find'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/tire-0.3.12/lib/tire/results/collection.rb:57:in `results'
        from /data/App/shared/bundled_gems/ruby/1.9.1/gems/tire-0.3.12/lib/tire/results/collection.rb:74:in `size'
        from (irb):30
        ...
```

You should really use `where(:id => ids).all` or `find_all_by_id(ids)` instead, that way the ids that are not found aren't simply fetched, without any exception.

Managing this in the app would be much harder, as the exception should be managed, and in the case of an error, it's hard to say which ids isn't there. And showing an error page just because a single records hasn't been found is really bad for the user.

**Comment by karmi** [comment]
`where(:id => ids)` is _ActiveRecord_ specific, not everybody uses that.

But yes, maybe we could go further to support _ActiveRecord_ in the future.

**Comment by xdmx** [comment]
Hi Karmi, yes, it's an ActiveRecord method, but I think that also without it that part should be managed better, without throwing an error when a single record is not found, but it should ignore it and load the others... I guess it's possible to do it also without using ActiveRecord

**Comment by SLM-Linus** [comment]
This is causing great trouble for us. We are inserting some objects in to the database inside a transaction. Somewhere in the transaction an error occurs and we do a rollback on the database. This causes objects to exist only in elasticsearch and not in the main storage (MySQL in our case).

It would be great if some means of preventing this could be provided. I am currently hacking our fork of Tire to use `where(id: ids)` instead of `find(ids)` in `collection.rb` but I would love it if any official means of getting around the problem could be released.

**Comment by jlsherrill** [comment]
Changing tire to use where instead of find would just be masking the problem (Tire not handling transaction rollbacks).  Active record provides an after_rollback hook that we'd probably want to use to simulate rolling back the transaction in ES (which would probably just involve reindexing or deleting the object).

Changing to use where(:id=>ids) would result in the search server still having the stale data, it would just be filtered when you load the AR models automatically.  For instances where you don't need to load the AR models (which is the majority of our queries), the data would still be wrong.

**Comment by SLM-Linus** [comment]
Yes exactly, I probably should have made that clearer in my post. I want a solution that does not use the hack described but I still use it right now since it works for us...

**Comment by karmi** [comment]
@xdmx @SLM-Linus See the attached commit -- you can now override the `Tire::Results::Collection#__find_records_by_ids` in your codebase for possibly correct behaviour. While it's not a solution, it's a workaround for the problem -- please ping me if it works in your case.

@jlsherrill You're right -- in many cases, the problem lies in using the `after_save/after_destroy` callbacks. For ActiveRecord, Tire really should use `after_commit/after_rollback` callbacks.

**Comment by karmi** [comment]
@xdmx @SLM-Linus Closing.

**Comment by atlantis** [comment]
To get the above monkey patch working I also had to override def __get_results_with_load and compact the results - otherwise a nil value would be returned in the results wherever there was a missing ActiveRecord model

**Comment by karmi** [comment]
@atlantis So you overloaded `__find_records_by_ids` with some AR-specific `where(id: …)` logic, but needed to overload `__get_results_with_load` as well? That would be really weird considering the logic in https://github.com/karmi/retire/blob/master/lib/tire/results/collection.rb#L144

**Comment by atlantis** [comment]
@karmi I think the deal is that __get_results_with_load returns the results of the @response['hits']['hits'].map block, and since there's no .compact at the end (which is the only thing I added when I overloaded the function), there will always be one array element per hit returned, regardless of whether it's in records[type] or not.  So when I iterated over search results, if AR failed to find a record then I'd end up with a nil at that position because .detect couldn't find that result.  Thanks for an awesome gem btw!
