### ISSUE TITLE
Tire.index

### ISSUE THREAD

**Issue by ghost** [karmi/retire#39]
instance_eval is taking over self in when giving this a block; there is no other option then that;

welI I cannot give register_percolator_query or any other method instance variables from my original class; as instance_eval is called on the index and down to the query

**Comment by karmi** [comment]
Could you provide some example code? You can access variables from the same scope, eg. `params` in controller. You cannot access _local_ variables across the "scope gates" (_def_, _class_, _module_)

**Comment by ghost** [comment]
At present this cannot be done

```
 Tire.index('photos') do |index|
    index.register_percolator_query("meta.username:#{self.username}") do |query|
      query.string "meta.username:#{self.username}"
   end
  end
```

**Comment by karmi** [comment]
I don't understand, still.

This works:

``` ruby
require 'rubygems'
require 'tire'

username = 'test'

Tire.index('photos') do |index|
 index.register_percolator_query("meta.username:#{username}") do |query|
   query.string "meta.username:#{username}"
 end
end
```

Of course `self.username` does not work in the `register_percolator_query`, since `self` is `Tire::Index` there, and rightly so.

In the block, you only have access to the context of enclosing scope. 

In our case, I'm happily doing something like this:

``` ruby
class Alert
  attr_accessor :name

  # ...

  def register_query
    name_escaped = Rack::Utils.escape(name)
    myclass.mydocs.elasticsearch_index.register_percolator_query(name_escaped) do |query|
      query.boolean &main_query
      query.boolean &keywords_query
    end
  end

end
```

By the way, why are you using the top level DSL such as `Tire.index` when clearly you have some entity such as `Photo`? Why don't you create a class for it and mix the _Tire_ methods into your class?

**Comment by hookercookerman** [comment]
yeah cool; thanks for the input;  very true about self; cheers
