### ISSUE TITLE
Serializing and deserializing searches

### ISSUE THREAD

**Issue by JamesHarrison** [karmi/retire#416]
Hi. In a site I'm porting from a pure MongoDB backend to ElasticSearch+Mongo I need to be able to serialize searches and deserialize them (then modify pagination parameters), then execute them. This is used for automatic page reloads and the like.

What I'm currently doing is something like this:

```
  @search = Tire.search 'images', size: @per_page, from: @skip_num, load: true do |search|
    search.query { all }
    search.filter :not, terms: { tag_ids: @hidden_tags }
    search.sort { by :created_at, 'desc' }
  end
  @images = @search.results
  @list_scope = Image.set_scope("All Images", @search, params)
```

The scope stores the result of to_hash on the search. This looks something like `{:query=>{:match_all=>{}}, :sort=>[{:created_at=>"desc"}], :filter=>{:not=>{:terms=>{:tag_ids=>["notwanted", "unwanted"]}}}}` (for instance).

This is so far, so good - but getting this back into a Tire.search call is proving troublesome. Doing `Tire.search('images', search_hash)` doesn't allow me to pass in any other options like pagination or load options. Am I missing a call to let me get from a hash to a search object properly? Passing the hash as options seems to partly work (`{"query":{"match_all":{}},"sort":[{"created_at":"desc"}],"filter":{"not":{"terms":{"tag_ids":["notwanted","unwanted"]}}},"options":{"load":true}}`) but doesn't actually load models or respect pagination.

Would be great to figure out how to do this.

Cheers,
James

**Comment by karmi** [comment]
Hi, I'm afraid that the outlined approach won't work 100% well, for the time being.

Effectively, you'll be serializing searches defined in the Tire DSL to Hashes, and then using completely different interface for performing the searches: using these Hashes instead of DSL. There are subtle discrepancies between those two interfaces at present, unfortunately.

Moreover, the [`MyModel.search`](https://github.com/karmi/tire/blob/master/lib/tire/model/search.rb#L30-100) API works either with simple query strings or a full-fledged block, forcing you to use the `Tire.search` interface to perform “freeform” queries and programming the database fetching etc. on top of that.

A better approach would be to identify and store search _parameters_ for the given search request, and passing them to prepared search definitions. One, often overlooked, strong point of _Tire_ are [boolean queries](http://karmi.github.com/tire/#section-Boolean_Queries), which allow you to decompose larger queries into smaller chunks, using lambdas for defining the components.

Based on the code snippet you've posted, it seems like this is something viable in your scenario -- in one of my apps, we're doing something similar, extracting the search definition into a Module containing `main_query`, `sources_query`, `keywords_query`, `highlight_options`, etc. methods. We then mix this module into various models and other classes where we need the search functionality. The module relies on a simple contract on the part of the containing component, such as access to `params` or `account` data structures. Have a look at this [gist](https://gist.github.com/83c93a8ba6a720979543) for inspiration. This way, the _account_ information (specific keywords, tags, ...) is persisted in the database and _parameters_ (eg. freeform fulltext queries, sorting, ...) are passed on the fly and can be serialized quite easily as JSON (and loaded back from a database).

The design is guided by the classic _“Separate things that change from things that stay the same”_ principle; what varies, usually, are different _parameters_ for fairly static _patterns_. I don't know if the idea applies to your scenario, but hopefully it's some food for thought.

**Comment by JamesHarrison** [comment]
Okay - having thought about this and had a look at your code, and how it'd apply to my situation here's what I'm thinking. We basically are using tire for everything, which means we're dealing with a lot of variations in queries, mostly in the search filters rather than query booleans. We're using filters (term/terms, numeric_range, mostly) for most of our stuff; our queries are all but in one case just 'match all'.

What I think I need to do is serialize the hash/store it, and then from that query, regenerate a new query using the DSL and the information from that stored hash. This way I can get relatively transparent query regeneration on deserialization, I think. The controller can still handle inserting the user-specific stuff into a search. The sorts of things where the serializable search is needed is, for instance, on drilldown into a result page, users can navigate within their results (combined with their account-specific query inclusions) from that page.

**Comment by karmi** [comment]
> We basically are using tire for everything, 

Cool :)

> (...) which means we're dealing with a lot of variations in queries, mostly in the search filters rather than query booleans. We're using filters (term/terms, numeric_range, mostly) for most of our stuff

When you use mostly filters, I think the whole serialization/deserialization story gets a bit simpler, since filters are effectively just tight wrappers around Ruby `Hash`. You need to keep track of the field(s) you're filtering on, and the `Hash` payload -- and that is quite easily stored in eg. Redis or elasticsearch itself.

> What I think I need to do is serialize the hash/store it, and then from that query, regenerate a new query using the DSL and the information from that stored hash.

Yes. Given it's filters, should be doable very well.

> The controller can still handle inserting the user-specific stuff into a search.

Exactly, like getting `current_user` and fetching her “preferences” for filtering, etc. It would be easy to implement something like a “saved search” feature (a la Apple's “Smart Folders”) in this way.

> The sorts of things where the serializable search is needed is, for instance, on drilldown into a result page, users can navigate within their results (combined with their account-specific query inclusions) from that page.

I'm not sure I understand the pagination part of the whole story, but then again, it's just parameters to the search method (or the `size`/`from` methods).

**Comment by karmi** [comment]
@JamesHarrison Closing or...?
