### ISSUE TITLE
Filter Facets should support full query DSL

### ISSUE THREAD

**Issue by ches** [karmi/retire#425]
[Filter Facet](http://www.elasticsearch.org/guide/reference/api/search/facets/filter-facet.html) support was added in #285, but the implementation limits it to `term` filtering only, while ES supports the full query DSL for this. Unfortunately it appears that fixing this will require a breaking API change, as the DSL probably should look just like query filters, as in:

``` ruby
facet 'received' do
  filter :term, :recipient_id => user.id
end
```

instead of currently:

``` ruby
facet 'received' do
  filter :recipient_id, user.id
end
```

(For reference, "filter facet" and "facet filter," as illustrated in #400, are not the same things :wink:).

I'll try to contribute a fix if I have some time to dig into the tests, at the moment I actually only need a `term` filter :grin:

**Comment by karmi** [comment]
I keep confusing ”filter facets” with “facet filters” no matter how I try :)

So, “facet filter” works with [support for full ES API](https://github.com/karmi/tire/blob/master/test/integration/facets_test.rb#L52-54), but “filter facets” are indeed tied to `term` filter.

The change you're proposing is of course absolutely warranted.

It does not have to be breaking, by the way, because we can keep the current behavior (which makes a reasonable default?) and use a block syntax for DSL definitions:

``` ruby
facet 'received' do
  filter do
   filter  :term, :recipient_id => user.id
  end
end
```

But the duplication in `filter` is certainly ugly. I think we can introduce an API breaking change here; it makes more sense.

**Comment by karmi** [comment]
Should be working now, see integration test in https://github.com/karmi/tire/blob/68e474a/test/integration/facets_test.rb#L242-246 for an example.

**Comment by ches** [comment]
Yay, thanks!
