### ISSUE TITLE
Unexpectedly returning all results

### ISSUE THREAD

**Issue by barmstrong** [karmi/retire#464]
I have this in my model:

``` ruby
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Tire::Model::Search
  include Tire::Model::Callbacks

  field :name, type: String
  field :email, type: String
  mapping do
    indexes :name
    indexes :email
  end
  def to_indexed_json
    {name: name, email: email}.to_json
  end
end
```

And I have a bunch of test users with emails like user1@example.com, user2@example.com, ... user10@example.com

Here is the weird part, when I search any of the following it returns the expected single user:

``` ruby
User.search("user2")
User.search("user2@example.co")
```

But then I search the email address exactly it returns _all users_:

``` ruby
User.search("user2@example.com")
```

In other words, an exact match on the email causes it return every user, whereas a partial match on the email returns just the one user as expected.

Any ideas?

**Comment by karmi** [comment]
Hi, this is certainly very weird... Could you post your mapping?

**Comment by karmi** [comment]
Actually no, it is not weird and it is not unexpected :)

Because you haven't specified an analyzer for your `e-mail` field, an address like `user1@example.com` ends up being split into: ["user1", "example.com"] when indexing -- and also when searching.

You can and should verify it with the Analyze API: http://localhost:9200/_analyze?text=user1@example.com&analyzer=standard

That means you're effectively searching for "example.com", and of course _all_ your documents match such a query.
The solution in your case is to either set the e-mail as `not_analyzed`, or preferably, to use the [multi-field](http://www.elasticsearch.org/guide/reference/mapping/multi-field-type.html) feature.

(Closing this for now, feel free to reopen if you have other problems.)
