### ISSUE TITLE
Pagination without a pagination gem

### ISSUE THREAD

**Issue by daveworth** [karmi/retire#509]
In cases where a model being indexed does not support pagination we can fake it by using something like:

``` ruby
Model.find_in_batches(batch_size: SOME_REASONABLE_CONSTANT) do |models|
  Model.index.import models
end
```

I will happily write this patch if you feel it would add to the projects.

Cheers,
Dave

**Comment by karmi** [comment]
Hi, sure -- but the problem is that `find_in_batches` is ActiveRecord specific, and there's no similar shared interface for ActiveModel. I'm wary about using ActiveRecord specific semantics...

What you describe is a perfect approach -- which should be used in client code, not in the library, in my opinion.

It would be hard to support every corner-case in the library and generic tasks, while it's very easy to write glue code like this to support specific cases.

What do you think?

**Comment by daveworth** [comment]
That is an _excellent_ point, that I hadn't considered.  I suppose some variety of mixin could add such a feature and then AR devs could opt-in.  That feels pretty heavy-weight but maybe lighter weight than adding Kaminari if you are never planning on displaying your objects in a paginated fashion in your app (which is admittedly rare).

I agree with you.  Let's close this and encourage pagination tools.  :+1:

**Comment by karmi** [comment]
Documentation> http://api.rubyonrails.org/classes/ActiveRecord/Batches.html#method-i-find_in_batches, http://guides.rubyonrails.org/active_record_querying.html#find_in_batches

Also check> karmi/tire#530
