### ISSUE TITLE
Bug: model with a 'has_many :matches' crashes app when indexed

### ISSUE THREAD

**Issue by robinator** [karmi/retire#525]
Hey,

I'm running into an error when I try to run `update_index` on a model of mine.  My model has a `has_many` association called `matches` which I believe is causing the problem.

I believe this is because tire is expecting the `matches=` method on a model.  The problem is that the `has_many` association does allow a `matchces=` method, but it doesn't want the data tire is trying to send it.  I'm not sure what the best solution would be, perhaps changing tires method to `_matches=`?

Is there another workaround I should be using?  I.e. updating the index directly somehow without using that method?

Below is a small example of what I'm talking about.

``` ruby
class User < ActiveRecord::Base
  has_many :matches

  ...code...

  include Tire::Model::Search
  include Tire::Model::Callbacks
end

@user = User.last
@user.update_index

NoMethodError: undefined method `each' for nil:NilClass
```

thanks

rob

**Comment by karmi** [comment]
Hi, there was a bug in the current [implementation](https://github.com/karmi/tire/blob/v0.5.1/lib/tire/model/search.rb#L196-L202) of `matches`, since it accessed the `@attributes` of the model directly.

The current master should fix the problem, can you try it in your codebase?

---

For completeness, this a isolated test code: http://hastebin.com/bivoposede.rb

**Comment by robinator** [comment]
Hey,

Just loaded up the fresh code and it works great!  Thanks for the help and the quick response.
