### ISSUE TITLE
Dynamic attributes for persistent modes

### ISSUE THREAD

**Issue by davekinkead** [karmi/retire#582]
@karmi, Tire + Elasticsearch is a fantasticly simple nosql persistence option for model data.

One thing I love about nosql is the schema-free nature of it meaning rapid prototyping is a breeze.  I often work with evolving data schema but the flexibility of ES is limited to some extend by the declarative requirements of Tire - requiring the property method for any attr that I want to access.

So is there an easy way of making the following work out of the box? Ideally I shouldn't have to change my model code if I need to add additional attribute on the fly.

```
class Foo
  include Tire::Model::Persistence
end

foo = Foo.create :name => 'foo', :bar => 'baz'
foo.bar # => I want 'baz' but currently can't access it
```

**Comment by davekinkead** [comment]
Looking under the hood a bit more, it seems the problem can be addressed with the following:

```
class Foo

  include Tire::Model::Persistence

  # => Override constructor to implement Tire Persistence
  def initialize(attrs={})
    attrs.each do |attr, value|
      # => call Tire's property method
      self.class.property attr unless self.class.property_types.keys.include? attr
      # => set instance variable
      instance_variable_set("@#{attr}", value)
    end
  end

end
```

Any thoughts to making this default behaviour?

**Comment by karmi** [comment]
Hi,

thanks for your thoughts and your code! I understand the issue, and understand why it would help when prototyping or working with heterogenous data.

The problem is, that a “sugar” like this quickly brings hypoglycemia on when you're not paying enough attention :) Models are initialized with heterogenous properties, those are saved into Elasticsearch with dynamic mapping, then somebody wants to sort on the `name` property and it does not work...

I do agree a default like this would be aligned with Elasticsearch's behaviour, but I'm just worried about the "sugar levels" here too much, based on experience.

That said, I think it would make a terrific [`tire-contrib`](https://github.com/karmi/tire-contrib) module, where you could use it like this:

``` ruby
    require 'tire'
    require 'tire/model/persistence/dynamic_attributes'

    class Foo
      include Tire::Model::Persistence
      include Tire::Model::Persistence::DynamicAttributes
    end
```

What do you think?

**Comment by davekinkead** [comment]
I have to admit that I haven't ventured into the tire-contrib module as the docs are very sparse. 

If you think that naming clashes could be a problem when searching, then the contrib module is fine.  I'm currently extending a base model class so this would do that in one _include_ line.

I'll have a sniff around  [tire-contrib](https://github.com/karmi/tire-contrib) and submit a pull request shortly.
