### ISSUE TITLE
Model update is not saved when elastic search is down

### ISSUE THREAD

**Issue by aufi** [karmi/retire#640]
Hi,

I would like ask if there is some "silent mode" which does not prevent saving record into database (mysql) when elasticsearch server is not running.

I tried use rescue_from MultiJson::DecodeError, Errno::ECONNREFUSED, exception was catched but model was not saved.

**Comment by nz** [comment]
Possibly related to #639 where the `after_commit` callback is concerned.

**Comment by karmi** [comment]
@aufi The exception being raised in that situation is `Errno::ECONNREFUSED`, as you would expect.

The transaction is being rolled back, however, because `MyModel.tire.update_index` (called from `after_save` hook) will return false even if you catch that exception.

In a situation like this, it's worth it to decide how would you resolve potential inconsistencies between your database and search index: do you want to store everything in the database, even when indexing fails, and resolve inconsistencies later? Then you probably shouldn't use the default `Callbacks` module and invest time in more sophisticated workflow. 

@nz Actually, this is the case where `after_commit` would be _harmful_, because it would introduce these inconsistencies -- some data would be in the database, some in the search index.

**Comment by aufi** [comment]
Thanks:)

In my view, not running Elasticsearch server should not prevent app models from save.

So, I changed Tire's model `Callbacks` from `after_save` to `after_commit` (and set up error notifications to reindex data manually).

**Comment by karmi** [comment]
> So, I changed Tire's model Callbacks from after_save to after_commit (and set up error notifications to reindex
> data manually).

By forking, monkey patching, or? Why not just roll your own indexing strategy then? See README for hints.

**Comment by aufi** [comment]
Just patch https://gist.github.com/aufi/5038549, the rest will be later..

**Comment by karmi** [comment]
An option, but this is not a generic solution and it would be _much_ easier for you to just call the `tire.update_index` inside your class definition, based on conditions you need to be matched, without all the Tire sauce around :)

**Comment by karmi** [comment]
An option, but this is not a generic solution and it would be _much_ easier for you to just call the `tire.update_index` inside your class definition, based on conditions you need to be matched, without all the Tire sauce around :)
