### ISSUE TITLE
Match query gives inconsistent results

### ISSUE THREAD

**Issue by brupm** [karmi/retire#650]
Inconsistent results when using boosting and match. Potentially an effective way to sort by rand() :sarcasm: 

https://gist.github.com/brupm/5062130

The results are very inconsistent, I must be confused as to when it is correct to use match.

**Comment by s1monw** [comment]
hey,

I don't think this is a tire issue not an ES issue. The problem here is that you are indexing documents that have all the same length (token wise) and you are searching on multi match wich builds a dismax top-level query and all the document will end up with the same score so the actual result list depends on the replicas the request is executed on and the order they answer the request. can you print the score and check if they are the same?

**Comment by karmi** [comment]
Yes, Simon's explanation is perfectly valid, this a synthetic data set and the scoring functions have too little to work on.

@brupm, try printing the scores as well:

``` ruby
m.results.to_a.map do |result|
  puts "* #{(result.first + ' ' + result.last).ljust(30)} | score: #{result._score}"
end
```

You'll notice groups of results with the same score, where the results will be sorted "randomly".

**Comment by s1monw** [comment]
even further if you set search_type = dfs_query_then_fetch it should be consistent score wise across the board. It also depends on the document frequencies here
