### ISSUE TITLE
Determine parent from record when indexing documents individually

### ISSUE THREAD

**Issue by fcheung** [karmi/retire#668]
At the moment setting the parent when indexing a single document requires that the parent option be passed to `store` and tire does not try and extract this information from the document (unlike `bulk_store`)

This makes it tricky to use parent/child when the document is stored in the index via the active model callbacks since the call to store is not directly in my hands.

I'll happily take a stab at this but I wondered whether there was a preferred approach. The first one that springs to mind would be for `store` to do what bulk_store does. Another would be closer to how update_index determines what percolator to use (although that feels a little heavy handed)

**Comment by karmi** [comment]
Hi Frederick, sorry for the silence.

Well, the [`Index#store`](https://github.com/karmi/tire/blob/master/lib/tire/index.rb#L135) presently extracts the `:parent` information from passed options. The trouble is, as you hint, in the `update_index` method.

Since we don't have any DSL support for parent/child in Tire yet, I think the easiest option would be to add an optional `options` argument to `update_index`, where you could pass the `:parent` option down the chain. Do you think this would be enough for your use case?

It would be nice to pass it automatically based on some model mapping introspection, but I think this would be better handled by a more robust DSL support. What do you think?

**Comment by fcheung** [comment]
Passing the option argument though update_index would be enough for me at the moment, but still makes things hard if you use the callbacks and you're in control of the call to update_index.

On the subject of the dsl, what would we need to do ? We'd need )at the very least ) to mark an attribute of the child  as the one that identifies the parent (and then use that as the default parent value throughout). Are you also thinking about work on the queries/filters ? I think those do work pretty well as things stand - I don't recall hacking those

**Comment by karmi** [comment]
> still makes things hard if you use the callbacks and you're in control of the call to update_index

Sorry --  do you mean _not_ in control of the call? I think that presently, using parent/child would require users to take indexing into their own hands, and not use the automatic callbacks. (Otherwise, we would need the introspection.)

> mark an attribute of the child as the one that identifies the parent

Yeah, and injecting it into mapping as the [`_parent`](http://www.elasticsearch.org/guide/reference/mapping/parent-field.html), that sounds good. There's no support for parent/child queries yet, IIRC you've added them some time ago in your fork?

**Comment by fcheung** [comment]
Sorry, yes, not in control. I forget what's in my fork versus not. I'll see if I can put something together that adds this to the mapping DSL and the query stuff is fairly straightforward

**Comment by karmi** [comment]
@fcheung Been pondering this for a while, and I think it's not worth it to add this support to the ActiveModel callbacks... I think for parent/child, one must index in a custom way anyway, and I'm wary of "false promises" here... What do you think? I'd vote to close this issue and return to it when time is right...

**Comment by fcheung** [comment]
I think you're right - I had some abortive attempts and didn't come up with something that had the right balance of versatility versus verboseness or complexity

**Comment by karmi** [comment]
I've added lot of info about handling indexing models manually to the README in the meantime, so closing this issue, if that's OK.
