### ISSUE TITLE
Are the update methods added via ActiveRecord integration threadsafe?

### ISSUE THREAD

**Issue by ghost** [karmi/retire#678]
Just having a look at the code, it seems that in general, the ActiveRecord Tire extension ultimately use an Index instance attached to the class (for example, see update_index in lib/tire/model/search.rb).

This seems like it wouldn't be threadsafe, however, as the methods in Index all drop the result of the last operation into a @response attribute. 

Is this correct, or am I missing something obvious (entirely possible)?

**Comment by karmi** [comment]
Could you elaborate on what is your specific concern regarding thread safety? Could you provide a code example? (Note: In regular search/update/etc operations, the `Tire::Index` instance isn't manipulated.)

**Comment by karmi** [comment]
@mowings-ts Any new info here? I don't think we [mutate state](https://github.com/celluloid/celluloid/wiki/Thread-safety-notes), but maybe there's something I'm missing.

**Comment by mowings** [comment]
Hi karmi. So, for us the concern is largely academic since we're not using the AR integration (mainly because we need a pretty decent separation between model and search logic for design reasons). 

However, just from looking at the code, it looks as if the after_save/destroy  callback installed by models/callbacks.rb invokes tire.update_index.

This method in turn calls index.store/remove when the model instance is saved or removed (model/persistence/storage.rb).

'index' when called on an instance looks to be fetching the class instance of the index (model/search.rb ):

```
    def index
      instance.class.tire.index
    end
```

All this would be fine, except that the store() method in index (along with other methods -- see index.rb) appears to save its results in an instance variable of the index itself and then decode it:

```
  @response = Configuration.client.post url, document
  MultiJson.decode(@response.body)
```

My concern is that this bit isn't threadsafe; if two threads happen to call after_save against model instances of the same class, a single (class-level) index instance will be used to  perform the save. This could potentially allow @response to get stepped on by either thread, creating a race condition. Seems like this issue would be more of an issue with GIL-less jruby, but I imagine it could happen with MRI as well.

Of course, I could have something wrong here or missed something. Cheers -- m

UPDATED: typo

**Comment by karmi** [comment]
@mowings I really can't say, that part of code might be prone to race conditions...

However, recently I did some short evaluations for the thread safety of the Curb client, and didn't run into issues, also some people run Tire in threaded environments and haven't reported Tire-related errors (though they report issues with Curb, see #144)

> (...) we need a pretty decent separation between model and search logic for design reasons

I'm really interested in that, so the library might support you better. If you can spare couple of minutes, can you elaborate a little bit?

**Comment by karmi** [comment]
Closing this for now, if that's OK, please feel free to ping back with more info if you have something!

**Comment by mowings** [comment]
Hi karmi --sorry to get back post-close. I simply meant that we really don't need the ActiveRecord integration -- we index the same model in vastly different ways depending on a number of factors. We also don;'t necessarily index immediately at save time. 

Tire without the AR integration is just fine for our purposes. Thanks again for the great work.
