### ISSUE TITLE
Index mapping is intermittently not working for Tire::Persistence model

### ISSUE THREAD

**Issue by radixhound** [karmi/retire#689]
We have created a Tire::Persistence model to store our data in ES. Initially we made the mistake of not using `:not_analyzed` for our regions which are strings like "US Hawaii" and thus the facets didn't work properly because they were being broken out into words.

We finally discovered that we had to set them as not_analyzed and we did basically this:

```
class IndexedThing
  include Tire::Model::Persistence

  mapping { indexes :region, index: :not_analyzed }

  property :region, index: :not_analyzed
end
```

This worked. Then we changed some more things, dropped and rebuilt the index and it stopped working. After some dropping and rebuilding it was working again. Currently it is not working and yesterday I spent a couple of hours trying to reproduce steps to get it to consistently fail so I could resolve it. No dice!

This is highly frustrating. I have tried looking into gem dependencies, such as multi_json and thought that it was the cause, but in the end, I could not consistently reproduce with and without.

I'm hoping that you can offer a suggestion as to why this would happen?

We are dropping and creating the index basically thus:

```
IndexedThing.index.delete
IndexedThing.create {id: 1, region: "US Hawaii"}
```

then we check the mapping and we see something like this

```
IndexedThing.index.mapping
=> {"indexed_thing"=>{"properties"=>{"region"=>{"type"=>"string"}}}}
```

but when it is working we see

```
{"indexed_thing"=>{"properties"=>{"region"=>{"type"=>"string", "index"=>"not_analyzed"}}}}
```

Is there a way, perhaps to explicity drop the mapping and rebuild it manually?

**Comment by karmi** [comment]
Hi, the reason why you're seeing inconsistent behaviour is because a) you're not creating the index explicitely, b) it all depends on whether you restart/reload your application/code, or not. Tire by default tries to create an index for the model with proper mappings/settings, when you start the application, and the index does not yet exists.

So, in your workflow, the correct sequence would be something like:

```
IndexedThing.tire.index.delete
IndexedThing.tire.create_elasticsearch_index
IndexedThing.create {id: 1, region: "US Hawaii"}
```

The `create_elasticsearch_index` effectively does `IndexedThing.tire.index.create(mappings: IndexedThing.tire.mapping_to_hash, settings: IndexedThing.tire.settings)`. Notice that the `rake tire:import:model` Rake task also allows you to re-create the index.

**Comment by karmi** [comment]
> Notice that the rake tire:import:model Rake task

Sorry, missed this is about `Tire::Model::Persistence`. Still, `IndexedThing.tire.create_elasticsearch_index` is the way to go.

**Comment by radixhound** [comment]
So helpful. Thank you!
