### ISSUE TITLE
Method name conflict with Mongoid: index

### ISSUE THREAD

**Issue by carterventures** [karmi/retire#7]
I'm using Mongoid and running into an issue when I attempt to use tire:

`/home/chris/.rvm/gems/ruby-1.9.2-p180/gems/tire-0.1.1/lib/tire/model/search.rb:54:in `index': wrong number of arguments (2 for 0) (ArgumentError)`

This is being thrown from my model where I've got the Mongoid "index" method for specifying that I want a field in my model indexed in MongoDB.

I'm relatively new to Ruby - is there a way I can namespace the class and instance methods from the Tire gem so I don't run into this?

**Comment by karmi** [comment]
Ah, thanks for the issue report.

It is solved in karmi/tire@9d51a28 and version 0.1.2.

And no, you cannot easily namespace it, because Tire just overloaded the Mongoid `index` method. I renamed the offending method for the time being, so you can use it. Please ping me if not.

However, the real solution is to wrap everything in Tire mixins in a proxy object, not add class/instance methods directly. I'll bite into this next week. See issues karmi/tire#8 a karmi/tire#9.
