### ISSUE TITLE
Is Tire (mostly) compatible with ElasticSearch 0.9.0

### ISSUE THREAD

**Issue by niuage** [karmi/retire#711]
From what I understood, ElasticSearch 0.9.0 stable release will be coming out "soon", and I was wondering if/when Tire will be compatible with it.

I saw that there are some breaking changes in the API, but I'm not sure how much it impacts Tire for the common use cases.

ps: I'm particularly interested in the new feature where we'll be able to sort by nested document attributes.

Thanks

**Comment by karmi** [comment]
There's no breaking change to the API and Tire is generally compatible for the common use cases. (Some tests such as `explanation_test` fail, but these are naming changes mostly.)

The new, more sophisticated sorting is not yet exposed in Tire, since its API is simple and takes just the pair of `field` and (sort) `direction`, the sorting support must be updated to allow passing Hash options.

Closing for the moment, if that's OK, please feel free to open separate issue for new issues/questions.
