### ISSUE TITLE
Index missing exception when using aliases and rotating the index.

### ISSUE THREAD

**Issue by radixhound** [karmi/retire#723]
Based on the advice here, we set up a process where we can rebuild the index by creating an index with a timestamp (e.g. 's_p_05052117') and aliasing it. This has been working for us but just recently we had a serious failure. It happened on some of our app servers but not all...

This was the error:

```
Tire::Search::SearchRequestFailed: 404 : {"error":"IndexMissingException[[s_p_05061750] missing]","status":404}
```

It seems like the ruby processes on these app servers got 'stuck' trying to query the previous version of the index, even though they are using the alias name to refer to the index. (Is that even possible?)

The servers are running apache + passenger (3.x). Restarting apache (+passenger) fixed the issue.

I'm hoping someone can give me some insight into why something like this could happen so I can track it down. Thanks!

**Comment by karmi** [comment]
That's weird, alias switching should really not depend on the Ruby process, since it's handled on the Elasticsearch side... Are you sure there wasn't something other going on? I have used frequently changing aliases without app restarts and haven't seen this issue... Are you sure the index object is not memoized somewhere etc?

This should be easy to model in an isolated test case, just have a simple Ruby process or app running, and then change the alias (via Tire or other means), and everything should continue working.

**Comment by radixhound** [comment]
Thanks for the response. As I was working on a reply I found the culprit. Brilliant question.

We have a button in the admin that triggers a manual rebuild of the index. It sets the name of the index to the new name and triggers the rebuild, but doesn't change the name back to default, so whichever ruby process is used to trigger a manual rebuild will be stuck on the old index. whew.
