### ISSUE TITLE
My code does not work under new 0.2.0 release

### ISSUE THREAD

**Issue by benzheren** [karmi/retire#77]
I have some simple tire search code within my rails 3.0.10 app. Today after I updated to 0.2.0, the code does not work anymore. There is no errors or warnings. My code snippet is like this:

```
  q = request.GET[:q]
  @s = Tire.search 'index_name' do
     query do
        string q 
     end
   end
```

**Comment by karmi** [comment]
Watch for deprecation notices on previous version, 0.1.16.

What "does not work" mean in this case? What is the expected and real outcome?

**Comment by benzheren** [comment]
Under 0.1.16, the above code is able to retrieve results back from backend. With the new 0.20.0, the returned results are always empty.

**Comment by karmi** [comment]
Is it possible to send a gist so I can try to recreate that? Very hard to give an answer otherwise.

**Comment by karmi** [comment]
Ping, any news?

**Comment by benzheren** [comment]
Karel, this is the gist: https://gist.github.com/1169884. 

By just updating tire version in my Gemfile to 0.2.0, this code does not work and return empty results. If I downgrade to 0.16.0, it works again. Is it because of some other dependency issue? If so, I can post my Gemfile as well. 

Thanks!

**Comment by karmi** [comment]
What if you run the command displayed by `puts @s.to_curl` in your gist directly? Are you still getting no results? Is the `curl` command different on 0.16 and 0.20?

**Comment by benzheren** [comment]
Okay, the problem is getting interesting. The curl is the same, but today when I tried out 0.2.0, it actually gave me error message like this:

```
NameError (uninitialized constant Webpage):
  app/controllers/search_controller.rb:12:in `ajax'
```

The `Webpage` is a type we defined in our elasticsearch. It seems that the 0.2.0 cannot recognize it correctly while the 0.16.0 has no problem with it.

**Comment by karmi** [comment]
I don't believe the problem is something changed between 0.1.16 and 0.2.0... The important thing is if _Tire_ is sending the same request to the ES, and it is, apparently. Tire, when used like in a snippet you posted, does not care about your Ruby classes. Again, watch for deprecation notices on 0.1.16.

While I can't and don't rule out the problem lies with _Tire_, there's just not enough information to analyze what's going on...

**Comment by karmi** [comment]
Any news on this?

**Comment by benzheren** [comment]
I have not figured out the problem yet and I am using 0.16.0 for now. But I just saw a new commit, which could be the cause of the problem: https://github.com/karmi/tire/commit/a0bbbf030e37e03fe882c6a92c265957ad3f2383

**Comment by karmi** [comment]
But you have not mentioned you've seen this error? You were seeing the generic `uninitialized constant XYZ` error?

There's just not enough information to replicate or at least understand what's going on....

**Comment by vijedi** [comment]
I'm new to tire so I'm not positive this observation is entirely relevant, I have a class called Profile in my rails application. Initially I was indexing it with the type "profiles". When tire went to create the search result, it gave me an error stating "uninitalized constant Profiles." Indexing this data with the type "profile" solved this issue for me.

**Comment by raff** [comment]
I have a slightly different use case that may help explain the problem:

In elasticsearch I have a collection of documents with type='app' (application). In Rails I created a Tire model named Case.

What I wanted to do was to configure the model to search with type='app' when accessing Case (similar to what you can do with ActiveRecord by explicitially setting the table name - table_name 'mytablename'). Up to 0.1.16 I was able to do that by redefining the class method document_type:

def self.document_type
  'app'
end

With this, the search was performed on /{index}/app and the returned object were instance of Case.

After updating tire (now at 0.3.3) this stopped working but I found both getter and setter for document_type so I changed my code to:

class Case : ...

  index_name 'myindex'
  document_type 'app'

end

This causes the search to be performed but then I get the error 'uninitialized constant App', that makes me think that this new version of tire simply tries to recreate the model only looking at the 'table name' (the elasticsearch 'type') instead of looking at the model configuration.

Note that while I also updated all my Rails stuff (ActiveRecord, ActiveModel, etc.) this doesn't seem to be the cause of the problem since downgrading tire to 0.1.16 makes the problem go away.

**Comment by benzheren** [comment]
Karel, I think several people have raised this issue. Is it possible to reopen it? Thanks!

**Comment by karmi** [comment]
Hi, I'll definitely look into that. Thanks @raff for the report. Reopening the issue.

**Comment by karmi** [comment]
Gentlemen, my sincere apologies.

The bug was real, very real, and also very obvious, once I had it in front of me -- was bit by this when consulting for a client.

As you can see from the [attached commit](https://github.com/karmi/tire/commit/ef26d4f0968f6db67ebe13ec77277526d1152b16), there were two things going on:
1. Within Rails, _Tire_ was trying to instantiate a (possibly incompatible) Ruby class matching `_type`, not the `Results::Item` wrapper.
2. Also within Rails, calling something like `Item#class` or `Item#inspect` would break the code, if it sailed throug the first problem.

This should be fixed right now. Sorry.

**Comment by karmi** [comment]
@benzheren, @raff, could you verify the problem went away with v0.3.6?

**Comment by benzheren** [comment]
@karmi, I will try out the latest code and let you know. Thanks!

**Comment by raff** [comment]
I did a quick test and it works! I'll do more testing later. Thanks!!!!

**Comment by benzheren** [comment]
The latest release works. However, the only thing I noticed that there was some change to the search response between 0.1.16 and 0.3.7. In some old codes I wrote I could modify the search result item directly, but now I have to do a `to_hash` to make it work.

**Comment by karmi** [comment]
Hmm, dunno what "modify the search results" mean, but yeah, the results returned are completely different.

On the 0.1 version, you received instances of your models (when you was lucky and your model was compatible :), on the 0.2 and up you receive instances of `Item`, and you can load the underlying model.

(I cannot imagine what purpose calling `to_hash` on a result would serve though...)
