### ISSUE TITLE
Wrap Tire functionality being mixed into a model in a "forwardable" proxy

### ISSUE THREAD

**Issue by karmi** [karmi/retire#8]
Wrap all Tire functionality into some "forwardable" object, and proxy every calls via this object.

The immediate reason for this is clash with [Mongoid](http://mongoid.org/docs/indexing.html) `index` method.
There are sure other cases like this.

**Comment by michaelklishin** [comment]
I think Sunspot at some point used #solr_index that was aliased to index if that wasn't defined already. This is a dead simple solution and it worked well for them. So I suggest doing that with `elastic_search_index` being the canonical method name.

**Comment by karmi** [comment]
Yeah, that's what @pacoguzman suggests in #9. There's no discussion it's the easiest, simplest way to accomplished the isolation.

I don't like the semantics of that, though. With `tire_index`, or `elasticsearch_index`, it still makes some sense. But what about `tire_mapping` or `elasticsearch_mapping` (and `settings`)? This has nothing to do with _Tire_ not _ElasticSearch_, but with the index corresponding to the model.

And then, what about eg. `MyClass.percolate`? That would have to be also „prefixed”, for consistency... How would the source look like when all the _Tire_ methods would be prefixed like this in a lame attempt of achieving isolation? How would the RDoc look like? Silly.

So, no easy answers here...

**Comment by michaelklishin** [comment]
Well, `elastic_search_mapping` still has something to do with ES in my opinion because if you stop using ES or provide full-text search at all, that method won't be necessary. I think it is not one of those cases when readability or semantics are the most important properties. The goal is to avoid method conflicts and still keep names meaningful (to me that means "hinting at ES"). Going for readability is likely to yield a solution that will be significantly more complex and will take days to develop & fully test out.

**Comment by karmi** [comment]
DONE! https://github.com/karmi/tire/blob/1255bfc9964dff2b053776ff7993d792022aff29/lib/tire/model/search.rb#L157-169

**Comment by karmi** [comment]
So, @antares, it _was_ a bit more of work in the end :), but I just could not have stand having a `Tire::Model::Search::ClassMethods::es_search` and `Tire::Model::Search::ClassMethods::es_index` and `es_<WHATEVER>` in the source.

Many thanks to my guiding light @svenfuchs for keeping me on the straight path! :)

**Comment by svenfuchs** [comment]
haha :)

you're welcome, buddy 

<3
