### ISSUE TITLE
Tire in high traffic environments overloads ElasticSearch

### ISSUE THREAD

**Issue by jmdfm** [karmi/retire#812]
Hi, 

Is there a way to batch updates from Tire to ElasticSearch using the Bulk API? I am on Heroku and using a hosted ElasticSearch provider and they have complained that the frequency of updates is too high, and that they should be batched. 

This seems like something Tire should be able to handle, but I can't seem to find any advice. 

Thanks

**Comment by karmi** [comment]
Hey, yeah, that might happen, though I'm a bit surprised your Elasticsearch provider complains about it :)

As always, what Tire provides "without configuration" is just some default. For custom indexing, the most maintainable and robust way is to implement it "manually" — I've added some info to the README recently about several strategies there.

For batching everything on your side, I'd approach it as a problem for messaging queue -- Redis for most cases, RabbitMQ for larger systems. You could just `RPUSH` events containing the payload (what to index where) to a list, and have a worker which would periodically `BLPOP` from the list, and when it gets say 10, 20, 100 items, it sends everything via a [bulk](https://github.com/karmi/tire/blob/master/test/integration/bulk_test.rb) API call.

In a system like this, double check that you have:
- Proper monitoring of workers in place
- Guards against excessive memory use (eg. ES is down, you keep pushing on list, Redis exhausts memory)
- Handling of failures, ie. what happens when the bulk API call is not successful
- An easy way to reindex everything for catastrophic scenarios

**Comment by karmi** [comment]
Closing, hope the note helped.
