### ISSUE TITLE
load: true when ES is out of sync with database

### ISSUE THREAD

**Issue by rdetert** [karmi/retire#890]
Right now I am autoloading models like so:

  def self.search(params)
    tire.search(load: true) do
      query { string params[:query], default_operator: "AND" } if params[:query].present?
      sort { by :created_at, 'desc' }
    end
  end

What if Elasticsearch is out of sync with the database. Is there anyway to make it silently ignore the records it can't load?

**Comment by mahemoff** [comment]
I've also encountered this just now as I've decided my app's views will just use ActiveRecords now instead of Tire's results, so I can use common infrastructure (e.g. a view to list active records).

This issue came up here too: http://stackoverflow.com/questions/15026612/rails-tire-elasticsearch-weird-error

Tire could probably do with a patch to use a query like `where(id: ids)` that will permit non-existing IDs. Nevertheless, here's the kernel of a workaround I made: https://gist.github.com/mahemoff/7251414

It does more than just avoid that error, as it also augments the records with result/hit info, and supports a custom query for efficiency purposes.

**Comment by karmi** [comment]
@mahemoff This has been debated over and over, please search the issues... We can't do `where(id: ids)`, since we have to work with ActiveModel, Mongoid, etc.

@rdetert You can overload [`__find_records_by_ids`](https://github.com/karmi/retire/blob/master/lib/tire/results/collection.rb#L155-L157), where you can use all ActiveRecord, Mongoid, or your-custom-ORM-specific logic.
